# Generated by Django 2.1.10 on 2019-07-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminspecaopc',
            name='operacao',
            field=models.CharField(default='novo', max_length=50),
            preserve_default=False,
        ),
    ]
