# Generated by Django 2.1.10 on 2019-08-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0002_iteminspecaopc_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerplanocontrole',
            name='pdfcriado',
            field=models.BooleanField(default=False),
        ),
    ]
