# Generated by Django 2.1.10 on 2019-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0003_headerplanocontrole_pdfcriado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerplanocontrole',
            name='mo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
