# Generated by Django 2.1.10 on 2019-08-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0004_auto_20190811_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspecaoplanocontrole',
            old_name='id_usuario',
            new_name='username_usuario',
        ),
    ]
