# Generated by Django 2.1.10 on 2019-08-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0005_auto_20190811_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerplanocontrole',
            name='datapdfcriado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
